@echo off
echo Starting SumAI Backend Server...
echo.
echo Installing dependencies...
pip install -r requirements.txt
echo.
echo Starting server...
uvicorn summ:app --host 0.0.0.0 --port 5000 --reload
pause 